"""
SIH 26090: Demand Forecast Run & Forecast Point Models
Implements immutable run-point architecture for classical and empirical time-series forecasting.
"""

from sqlalchemy import Column, String, Integer, Float, Text, ForeignKey, DateTime, JSON
from sqlalchemy.orm import relationship

from backend.app.core.database import Base
from backend.app.models.base import TimestampMixin, generate_uuid, utc_now


class DemandForecastRun(Base, TimestampMixin):
    """
    Immutable execution record of a demand forecasting run.
    Stores model identification, parameters, validation error metrics,
    and training/validation/test chronological windows.
    """
    __tablename__ = "demand_forecast_runs"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    craft_id = Column(String(36), ForeignKey("crafts.id", ondelete="CASCADE"), nullable=True, index=True)
    craft_category_id = Column(String(36), ForeignKey("craft_categories.id", ondelete="SET NULL"), nullable=True, index=True)
    geography_state = Column(String(100), nullable=True, index=True)

    model_name = Column(String(50), nullable=False, doc="WMA, HOLT_WINTERS, NAIVE_BASELINE")
    model_version = Column(String(30), nullable=False, default="DEMAND_ENGINE_V1")

    # Chronological Evaluation Windows (Strict No-Leakage Boundaries)
    training_start_date = Column(DateTime(timezone=True), nullable=False)
    training_end_date = Column(DateTime(timezone=True), nullable=False)
    validation_start_date = Column(DateTime(timezone=True), nullable=True)
    validation_end_date = Column(DateTime(timezone=True), nullable=True)
    test_start_date = Column(DateTime(timezone=True), nullable=True)
    test_end_date = Column(DateTime(timezone=True), nullable=True)

    observation_count = Column(Integer, nullable=False)
    validation_mape = Column(Float, nullable=True, doc="Mean Absolute Percentage Error on held-out validation set")
    validation_rmse = Column(Float, nullable=True, doc="Root Mean Squared Error")

    status = Column(
        String(30),
        nullable=False,
        default="COMPLETED",
        index=True,
        doc="COMPLETED, FAILED, INSUFFICIENT_HISTORY, INSUFFICIENT_DATA_QUALITY"
    )
    limitations_notes = Column(Text, nullable=True)
    parameters_json = Column(JSON, default=dict, nullable=False)

    # Relationships
    craft = relationship("Craft")
    craft_category = relationship("CraftCategory")
    points = relationship("DemandForecastPoint", back_populates="run", cascade="all, delete-orphan", order_by="DemandForecastPoint.forecast_period_year, DemandForecastPoint.forecast_period_month")


class DemandForecastPoint(Base):
    """
    Individual projected time period generated by a specific DemandForecastRun.
    Preserves projected index, optional statistically justified confidence bounds,
    and explicit honesty state.
    """
    __tablename__ = "demand_forecast_points"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    run_id = Column(String(36), ForeignKey("demand_forecast_runs.id", ondelete="CASCADE"), nullable=False, index=True)

    forecast_period_month = Column(Integer, nullable=False)
    forecast_period_year = Column(Integer, nullable=False)
    projected_demand_index = Column(Float, nullable=True, doc="Normalized demand index (100.0 = baseline)")
    projected_unit_volume = Column(Integer, nullable=True, doc="Estimated physical units if volume data sufficient")

    # Statistically justified uncertainty interval (None if uncalibrated/unjustified)
    uncertainty_lower = Column(Float, nullable=True)
    uncertainty_upper = Column(Float, nullable=True)

    data_sufficiency_status = Column(
        String(40),
        nullable=False,
        default="FORECAST_AVAILABLE",
        doc="FORECAST_AVAILABLE, INSUFFICIENT_HISTORY, INSUFFICIENT_DATA_QUALITY, FORECAST_UNAVAILABLE"
    )
    explanation_note = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), default=utc_now, nullable=False)

    # Relationship
    run = relationship("DemandForecastRun", back_populates="points")
